apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  labels:
    app: mariadb
type: Opaque
data:
  # root password for MySQL
  # echo -n varMyRootPass | base64
  root-pass: dmFyTXlSb290UGFzcw==
  # user for MySQL
  # echo -n varMyDBUser | base64
  user: dmFyTXlEQlVzZXI=
  # password for the second MySQL user
  # echo -n varMyDBPass | base64
  pass: dmFyTXlEQlBhc3M=
  # password for the second Magento DB
  # echo -n varMyRootPass | base64
  name: bWFnZW50b192YW5pbGxh

---

apiVersion: v1
kind: Secret
metadata:
  name: magento-secrets
  labels:
    app: magento
type: Opaque
data:
  # Name of Magento DB
  # echo -n magento_vanilla | base64
  db_name: bWFnZW50b192YW5pbGxh
  # echo -n admin | base64
  admin_user: YWRtaW4=
  # echo -n admin_password | base64
  admin_pass: YWRtaW5fcGFzc3dvcmQ=

---
  
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  labels:
    app: redis
type: Opaque
data:
  # password for the second MySQL user
  # the actual password is varMyDBPass
  # echo -n redisPassword | base64
  password: cmVkaXNQYXNzd29yZA==

---
  
apiVersion: v1
kind: Secret
metadata:
  name: varnish-secrets
  labels:
    app: varnish
type: Opaque
data:
  # password for the second MySQL user
  # the actual password is varMyDBPass
  # echo -n cXNQYXNmVk9yZAazd2 | base64
  auth_key: Y1hOUVlYTm1Wazl5WkFhemQy
