apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  # Set scn to mount from home
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    #path: "/tmp/data"
    path: "/hosthome/sam/var/data/k8s/magento-vanilla-dev/pv/database"
