apiVersion: v1
kind: PersistentVolume
metadata:
  name: webroot-pv
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  # Set scn to mount from home
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  hostPath:
    #path: "/tmp/data"
    path: "/hosthome/sam/var/data/k8s/magento-vanilla-dev/pv/webroot"
