#
# DB ingress
#
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service-dev
  labels:
    app: mariadb
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mariadb