apiVersion: v1
kind: PersistentVolume
metadata:
  name: magento-pv-volume
  namespace: magento-vanilla
  labels:
    type: local
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    #path: "/tmp/data"
    path: "/hosthome/sam/var/data/magento-vanilla/pv/magento-pv-volume"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: magento-pv-claim
  namespace: magento-vanilla
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-pv-claim
  namespace: magento-vanilla
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-pv-claim
  namespace: magento-vanilla
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi